apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: bonusservice
  name: bonusservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: bonusservice
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: bonusservice
    spec:
      imagePullSecrets:
      - name: registry-key    
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: variables
              key: ASPNETCORE_ENVIRONMENT
        image: registry.gitlab.nvg.ru/ezs/bonusservice:latest
        imagePullPolicy: "Always"
        name: bonusservice
        livenessProbe:
          exec:
            command:
            - netstat -an | grep 9098 > /dev/null; if [ 0 != $? ]; then exit 1; fi;
          failureThreshold: 3
          periodSeconds: 15
          timeoutSeconds: 15        
        # ports:
        # - containerPort: 9098
        # resources:
        #   limits:
        #     cpu: 0.7
        #     memory: 512M
        # volumeMounts:
        # - mountPath: /app/log
        #   name: ezs-log        
      hostname: bonusservice
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: ezs-log
        persistentVolumeClaim:
          claimName: ezs-log
status: {}
