apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: bonusservice
  name: bonusservice
spec:
  ports:
  - name: "9098"
    port: 9098
    targetPort: 9098
  selector:
    io.kompose.service: bonusservice
status:
  loadBalancer: {}
