apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: bonusservice
  name: bonusservice
spec:
  ports:
  - name: "9100"
    port: 9100
    targetPort: 9100
  selector:
    io.kompose.service: bonusservice
status:
  loadBalancer: {}
